on:
  push:
  # Triggers the workflow on push or pull request events but only for the main branch
    branches: [ main ]
    paths-ignore: [ active-monitor/** ]

name: Deploy!

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        project_id: agile-islands-example
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true  # Set to true to authenticate the Cloud Run action

    - name: Authorize Docker push
      run: gcloud auth configure-docker
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        build-args: REACT_APP_GIT_SHA=${{ github.sha }}
        push: true
        tags: |
          gcr.io/agile-islands-example/moody:latest
          gcr.io/agile-islands-example/moody:${{ github.sha }}
        cache-from: type=registry,ref=gcr.io/agile-islands-example/moody:cache
        cache-to: type=inline,ref=gcr.io/agile-islands-example/moody:cache

    - name: Deploy Canary to Cloud Run
      id: deploy-canary
      uses: google-github-actions/deploy-cloudrun@v0.6.0
      with:
        image: gcr.io/agile-islands-example/moody:${{ github.sha }}
        service: moody
        region: europe-west1
        tag: next
        no_traffic: true
        credentials: ${{ secrets.GCP_SA_KEY }}

    - name: Show Output
      run: echo ${{ steps.deploy-canary.outputs.url }}

    - name: Run Smoke Tests on Canary
      working-directory: ./active-monitor
      run: | 
        yarn
        yarn test

    - name: Shift Traffic to Next Version
      id: shift-traffic
      uses: google-github-actions/deploy-cloudrun@v0.6.0
      with:
        service: moody
        region: europe-west1
        tag_traffic: next=100
        credentials: ${{ secrets.GCP_SA_KEY }}
