on:
  push:
  # Triggers the workflow on push or pull request events but only for the main branch
    branches: [ main ]
    paths-ignore: [ systemtest/** ]

name: Deploy!

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        project_id: agile-islands-example
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true  # Set to true to authenticate the Cloud Run action

    - name: Authorize Docker push
      run: gcloud auth configure-docker
    
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          gcr.io/agile-islands-example/moody:latest
          gcr.io/agile-islands-example/moody:${{ github.sha }}

    - name: Deploy to Cloud Run
      id: deploy
      uses: google-github-actions/deploy-cloudrun@v0.6.0
      with:
        image: gcr.io/agile-islands-example/moody:${{ github.sha }}
        service: agile-islands-example
        region: europe-west1
        credentials: ${{ secrets.GCP_SA_KEY }}

    - name: Show Output
      run: echo ${{ steps.deploy.outputs.url }}
