on: workflow_dispatch

name: Shift traffic to next version

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Setup Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        project_id: agile-islands-example
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true  # Set to true to authenticate the Cloud Run action

    - name: Shift Traffic to New Version
      id: deploy
      uses: google-github-actions/deploy-cloudrun@v0.6.0
      with:
        image: gcr.io/agile-islands-example/moody:${{ github.sha }}
        service: agile-islands-example
        region: europe-west1
        tag_traffic: next=100
        credentials: ${{ secrets.GCP_SA_KEY }}

    - name: Show Output
      run: echo ${{ steps.deploy.outputs.url }}
